// Shared Tailwind aliases. Change colours only in tokens.css.

        tailwind.config = {
            darkMode: "class",
            theme: {
                extend: {
                    "colors": {
  "surface-bright": "rgb(from var(--surface-raised) r g b / <alpha-value>)",
  "on-secondary-container": "rgb(from var(--text-primary) r g b / <alpha-value>)",
  "on-error-container": "rgb(from var(--error) r g b / <alpha-value>)",
  "on-surface-variant": "rgb(from var(--text-muted) r g b / <alpha-value>)",
  "on-primary-fixed": "rgb(from var(--brand-primary) r g b / <alpha-value>)",
  "error": "rgb(from var(--error) r g b / <alpha-value>)",
  "surface-variant": "rgb(from var(--surface-strong) r g b / <alpha-value>)",
  "background": "rgb(from var(--surface) r g b / <alpha-value>)",
  "tertiary-fixed": "rgb(from var(--brand-subtle) r g b / <alpha-value>)",
  "on-surface": "rgb(from var(--text-primary) r g b / <alpha-value>)",
  "tertiary-fixed-dim": "rgb(from var(--brand-subtle) r g b / <alpha-value>)",
  "on-tertiary-container": "rgb(from var(--text-inverse) r g b / <alpha-value>)",
  "primary-fixed": "rgb(from var(--brand-subtle) r g b / <alpha-value>)",
  "on-secondary-fixed": "rgb(from var(--text-primary) r g b / <alpha-value>)",
  "secondary-fixed": "rgb(from var(--brand-action) r g b / <alpha-value>)",
  "outline": "rgb(from var(--text-muted) r g b / <alpha-value>)",
  "error-container": "rgb(from var(--error-subtle) r g b / <alpha-value>)",
  "outline-variant": "rgb(from var(--border) r g b / <alpha-value>)",
  "surface-container-low": "rgb(from var(--surface-muted) r g b / <alpha-value>)",
  "surface-container-high": "rgb(from var(--surface-strong) r g b / <alpha-value>)",
  "surface-container-highest": "rgb(from var(--surface-strong) r g b / <alpha-value>)",
  "on-secondary": "rgb(from var(--text-primary) r g b / <alpha-value>)",
  "on-primary-fixed-variant": "rgb(from var(--brand-primary) r g b / <alpha-value>)",
  "on-tertiary-fixed-variant": "rgb(from var(--brand-primary) r g b / <alpha-value>)",
  "inverse-on-surface": "rgb(from var(--text-inverse) r g b / <alpha-value>)",
  "on-tertiary": "rgb(from var(--text-inverse) r g b / <alpha-value>)",
  "tertiary": "rgb(from var(--brand-primary) r g b / <alpha-value>)",
  "on-background": "rgb(from var(--text-primary) r g b / <alpha-value>)",
  "surface-dim": "rgb(from var(--surface-strong) r g b / <alpha-value>)",
  "tertiary-container": "rgb(from var(--brand-primary) r g b / <alpha-value>)",
  "inverse-surface": "rgb(from var(--text-primary) r g b / <alpha-value>)",
  "surface-container": "rgb(from var(--surface-strong) r g b / <alpha-value>)",
  "surface": "rgb(from var(--surface) r g b / <alpha-value>)",
  "secondary-fixed-dim": "rgb(from var(--brand-action) r g b / <alpha-value>)",
  "secondary-container": "rgb(from var(--brand-action) r g b / <alpha-value>)",
  "surface-container-lowest": "rgb(from var(--surface-raised) r g b / <alpha-value>)",
  "secondary": "rgb(from var(--brand-primary) r g b / <alpha-value>)",
  "on-primary": "rgb(from var(--text-inverse) r g b / <alpha-value>)",
  "inverse-primary": "rgb(from var(--brand-subtle) r g b / <alpha-value>)",
  "surface-tint": "rgb(from var(--brand-primary) r g b / <alpha-value>)",
  "primary": "rgb(from var(--brand-primary) r g b / <alpha-value>)",
  "primary-fixed-dim": "rgb(from var(--brand-subtle) r g b / <alpha-value>)",
  "on-secondary-fixed-variant": "rgb(from var(--text-primary) r g b / <alpha-value>)",
  "primary-container": "rgb(from var(--brand-primary) r g b / <alpha-value>)",
  "on-error": "rgb(from var(--text-inverse) r g b / <alpha-value>)",
  "on-tertiary-fixed": "rgb(from var(--brand-primary) r g b / <alpha-value>)",
  "on-primary-container": "rgb(from var(--text-inverse) r g b / <alpha-value>)",
  "action": "rgb(from var(--brand-action) r g b / <alpha-value>)",
  "action-ink": "rgb(from var(--action-ink) r g b / <alpha-value>)",
  "success": "rgb(from var(--success) r g b / <alpha-value>)",
  "success-subtle": "rgb(from var(--success-subtle) r g b / <alpha-value>)",
  "success-border": "rgb(from var(--success-border) r g b / <alpha-value>)",
  "warning": "rgb(from var(--warning) r g b / <alpha-value>)",
  "warning-subtle": "rgb(from var(--warning-subtle) r g b / <alpha-value>)",
  "error-border": "rgb(from var(--error-border) r g b / <alpha-value>)",
  "white": "rgb(from var(--surface-raised) r g b / <alpha-value>)",
  "black": "rgb(from var(--text-primary) r g b / <alpha-value>)",
  "text-muted": "rgb(from var(--text-muted) r g b / <alpha-value>)",
  "brand-subtle": "rgb(from var(--brand-subtle) r g b / <alpha-value>)"
},
                    "boxShadow": {"sm":"0 1px 3px var(--shadow)","DEFAULT":"0 2px 8px var(--shadow)","md":"0 4px 16px var(--shadow)","lg":"0 8px 24px var(--shadow)","xl":"0 12px 32px var(--shadow)","card":"0 4px 20px var(--shadow)"},
"borderRadius": {
                        "DEFAULT": "0.25rem",
                        "lg": "0.5rem",
                        "xl": "0.75rem",
                        "full": "9999px"
                    },
                    "spacing": {
                        "margin-desktop": "40px",
                        "unit": "8px",
                        "container-max": "1280px",
                        "gutter": "24px",
                        "margin-mobile": "16px"
                    },
                    "fontFamily": {
                        "body-lg": ["Inter"],
                        "headline-md": ["Montserrat"],
                        "label-sm": ["Inter"],
                        "display-lg": ["Montserrat"],
                        "headline-lg": ["Montserrat"],
                        "label-md": ["Inter"],
                        "headline-lg-mobile": ["Montserrat"],
                        "body-md": ["Inter"]
                    },
                    "fontSize": {
                        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
                        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
                        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "600"}],
                        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
                        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500"}],
                        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
                        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
                    }
                },
            },
        }
    