/** Data only: adding another character requires a config, not another builder. */
const shared = {
  torso: { width: 0.78, height: 0.59, depth: 0.55 },
  head: { width: 1.1, height: 0.94, depth: 0.78, shape: "rounded" },
  limbs: {
    upperArm: 0.37,
    forearm: 0.35,
    thigh: 0.3,
    shin: 0.3,
    armRadius: 0.13,
    legRadius: 0.145,
  },
  colors: {
    body: "#f3f2ed",
    vest: "#b2f52c",
    stripe: "#c5cbd0",
    screen: "#080b0e",
    joint: "#bdc1bc",
  },
  accessories: { rings: true },
  hipHeight: 0.625,
  strideScale: 0.7,
  reach: {
    approach: 0.52,
    carryForward: 0.43,
    carryHeight: 0.26,
    strikeForward: 0.42,
  },
  screen: { width: 0.66, height: 0.53, radius: 0.13, offsetY: 0.015 },
};
export const BOT_PRESETS = {
  priya: {
    ...shared,
    name: "Priya",
    tool: "magnifier",
    personality: {
      tempo: 1.15,
      walkSpeed: 1.65,
      turnTime: 0.28,
      bob: 1,
      energy: 1,
    },
  },
  nour: {
    ...shared,
    name: "Nour",
    tool: "tablet",
    personality: {
      tempo: 1.25,
      walkSpeed: 1.75,
      turnTime: 0.3,
      bob: 1.35,
      energy: 1.2,
    },
    torso: { width: 0.84, height: 0.67, depth: 0.59 },
    head: { width: 1.16, height: 0.96, depth: 0.8, shape: "dome" },
    colors: { ...shared.colors, body: "#e8b638" },
    accessories: { antenna: true },
  },
  ellie: {
    ...shared,
    name: "Ellie",
    tool: "stylus",
    hipHeight: 0.58,
    limbs: { ...shared.limbs, thigh: 0.28, shin: 0.28 },
    personality: {
      tempo: 1.05,
      walkSpeed: 1.35,
      turnTime: 0.4,
      bob: 0.65,
      energy: 0.75,
    },
    torso: { width: 0.85, height: 0.55, depth: 0.62 },
    head: {
      width: 1.07,
      height: 0.9,
      depth: 0.77,
      shape: "hood",
      radius: 0.34,
    },
    colors: { ...shared.colors, body: "#51b0b4" },
    accessories: {},
  },
  omar: {
    ...shared,
    name: "Omar",
    tool: "wrench",
    personality: {
      tempo: 0.95,
      walkSpeed: 1.25,
      turnTime: 0.4,
      bob: 1.25,
      energy: 1.35,
    },
    torso: { width: 1.03, height: 0.63, depth: 0.68, roundness: 0.19 },
    head: {
      width: 1.33,
      height: 0.96,
      depth: 0.84,
      shape: "box",
      radius: 0.22,
    },
    limbs: { ...shared.limbs, armRadius: 0.16, legRadius: 0.17 },
    colors: { ...shared.colors, body: "#51545b" },
    accessories: {},
  },
  sami: {
    ...shared,
    name: "Sami",
    tool: "clipboard",
    hipHeight: 0.6,
    limbs: { ...shared.limbs, thigh: 0.29, shin: 0.29 },
    personality: {
      tempo: 1.35,
      walkSpeed: 1.9,
      turnTime: 0.24,
      bob: 0.6,
      energy: 0.85,
    },
    torso: { width: 0.98, height: 0.57, depth: 0.64 },
    head: { width: 1.31, height: 0.79, depth: 0.79, shape: "wide" },
    colors: { ...shared.colors, body: "#263e61" },
    accessories: { chestPanel: true },
  },
};
export function resolveConfig(config = {}) {
  return {
    ...shared,
    ...config,
    torso: { ...shared.torso, ...config.torso },
    head: { ...shared.head, ...config.head },
    limbs: { ...shared.limbs, ...config.limbs },
    colors: { ...shared.colors, ...config.colors },
    accessories: { ...config.accessories },
    screen: { ...shared.screen, ...config.screen },
    reach: { ...shared.reach, ...config.reach },
    personality: {
      tempo: 1.15,
      walkSpeed: 1.65,
      turnTime: 0.28,
      bob: 1,
      energy: 1,
      ...config.personality,
    },
  };
}
